### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jsbackus** [rss2email/rss2email#1]
Need to update the README to note the change of location, etc.

**Comment by Lenbok** [comment]
Heya, I just switched to the dev branch and so far things seem pretty good. I had to make a couple of changes to my config before things would work, which might be worth noting in the readme or release notes:

smtp-ssl-protocol has been removed (I needed to remove from my config)
smtp-server doesn't support host:port any more (I had to remove the port from my config)

**Comment by jsbackus** [comment]
Hi @Lenbok, sorry for taking so long to get back to you! Glad dev seems to be working for you. Agreed re: noting changes, though I would like to see us add migration support. Additionally, the config should die on no longer supported config keys. It should just ignore them, or worst case, issue a warning. I'll create a new issue...

**Comment by jsbackus** [comment]
See #8 and #9.
