### ISSUE TITLE
Support for “multipart/alternative”

### ISSUE THREAD

**Issue by mawis** [rss2email/rss2email#101]
Currently rss2email either sends the e-mail messages in plain text or in HTML, depending on the presence of the setting `html-mail = True`.

I don't read the messages generated by rss2email always on the same device. Actually when I read them on my mobile I much prefer the HTML formatting – while reading the mails on my desktop PC (using `mutt`) I much prefer the text encoding.

Normally with e-mails this is no problem as the typical standard is to send e-mails in `multipart/alternative` encoding having one part in plain text and the other in HTML. With rss2email this currently doesn't seem to be possible, while rss2email is already able to generate both encodings.

I'd like to see either a setting, that both encodings using `multipart/alternative` are used for sending e-mails or to automatically include a plain text alternative if rss2email is set up to send out HTML e-mails.

**Comment by Ekleog** [comment]
Done with #158, thank you @boyska!
