### ISSUE TITLE
Add ability to control address family (IPv4, IPv6, either)

### ISSUE THREAD

**Issue by rayvd** [rss2email/rss2email#107]
Ran into an issue where I was unable to connect to a feed.  Turns out the issue was only with IPv6 but I had no (easy) way to tell rss2email to prefer IPv4.

My quick & dirty fix was to edit `/etc/gai.conf`:

~~~
precedence ::ffff:0:0/96  100
~~~

This tells glibc's DNS lookup routines to give precedence to IPv4 addresses rather than IPv6.

Rather than mucking with a global glic setting, It would be nice to toggle this behavior with a CLI parameter, specify as a global default in the config and be able to override per feed.

**Comment by Ekleog** [comment]
I don't really think `rss2email` should support particular knobs for sending to IPv4 vs. IPv6: IPv* reachability issues are (almost) always system-wide, and it makes sense to fix them system-wide, even though potentially only `rss2email` triggers the issue.

If you really want this, could you give examples of other software that support manually specifying the network family? Off the top of my head I can't think of any that'd support anything over `https://1.2.3.4/foo/bar`, which `rss2email` should already support (but won't work if the recipient checks the `Host` header).

Also, maybe you could work around the lack of `Host` header with `bonus-header = "Host: foo"`, though I'm not at all sure it'd work

**Comment by rayvd** [comment]
Hmm.  Obviously both `cURL` and `wget` support this (`cURL` was how I troubleshot this, in fact), but their purpose is quite different I suppose.  `w3m` has this knob as a console-based web browser.  I didn't check `elinks`.

Your points are well taken though.  Perhaps I should wishing that Python's underlying network stack could could be influenced via a user-scoped environment variable.

In my specific case, I suspect the server side's IPv6 stack is failing them and I should let them know.

**Comment by Ekleog** [comment]
Closing, as there is little value in keeping this open I think. Sorry about that, and hope you can solve your networking woes!

**Comment by rayvd** [comment]
No worries.  I've been able to solve my particular issue another way.
