### ISSUE TITLE
How do I add feeds with names that contain spaces?

### ISSUE THREAD

**Issue by Hund** [rss2email/rss2email#111]
I just installed rss2email to check it out and I'm having issues with adding feeds that uses two words or more in their names.

What am I doing wrong? I tried using bith single and double quotes without any success.

**Comment by Ekleog** [comment]
Hmm… I'm not sure feeds that use two words in their names are supported. Have you tried just changing the name to not have a space but replace it by eg. a `-`, while still keeping the same URL? It should work :)

**Comment by Hund** [comment]
I guess that could work as a workaround. :)
