### ISSUE TITLE
Managing feeds by email

### ISSUE THREAD

**Issue by nikaro** [rss2email/rss2email#115]
What do you think about adding the possibility to manage feeds (add/delete and may be others actions too) by emails ? This could be handful to manage your feeds from somewhere you do not have a SSH access to "rss2email server".

For the example the following email would add a new feed:
```
From: authorized.sender@example.net
To: managed.mailbox@example.net
Subject: r2e add MyNewFeed

https://blog.example.net/feed/
```

`rss2email` would parse the subject according to a defined prefix (default to `r2e`) and from a defined sender if defined.

Let me know what do you think about it.

**Comment by auouymous** [comment]
Email is not encrypted and anyone can spoof the authorized sender. Everyone would have access to these commands, and any vulnerabilities in the email command parser would become remote vulnerabilities for the host.

This also requires support to read emails from local mbox, mh and maildir. And the title of your PR suggests it should also check a remote imap or pop3 server.

Would it scan emails in the 'run' command or a new command? There could be a 24 hour or more delay before the email is read if 'run' is only called once a day, or longer.

**Comment by nikaro** [comment]
Le 2020-05-30 23:29, auouymous a écrit :
> Email is not encrypted and anyone can spoof the authorized sender.
> Everyone would have access to these commands, and any vulnerabilities
> in the email command parser would become remote vulnerabilities for
> the host.

You are right... and i don't know if there is something we can to to
mitigate this. But it would be an issue for everything else using the
Python email parsing library, so probably quickly fixed when discovered.
Anyway, if your mail server allow spoofed sender to deliver emails to
local mailboxes i think you already have a problem.

> This also requires support to read emails from local mbox, mh and
> maildir. And the title of your PR suggests it should also check a
> remote imap or pop3 server.

Actually i was thinking about management through IMAP, that's my use
case. I don't know what is the workflow in use when someone use
rss2email with maildir and others.

> Would it scan emails in the 'run' command or a new command? There
> could be a 24 hour or more delay before the email is read if 'run' is
> only called once a day, or longer.

It would be another command. I used `imapmgt` for now. And i could
easily add a configurable delay before `rss2mail` parse the email. It
could be a kind of a mitigation for the first issue you raised, letting
some time for the mailbox owner to review the "commands emails".

**Comment by Ekleog** [comment]
Nicolas Karolak <notifications@github.com> writes:
> Le 2020-05-30 23:29, auouymous a écrit :
>> Email is not encrypted and anyone can spoof the authorized sender.
>> Everyone would have access to these commands, and any vulnerabilities
>> in the email command parser would become remote vulnerabilities for
>> the host.
>
> You are right... and i don't know if there is something we can to to
> mitigate this. But it would be an issue for everything else using the
> Python email parsing library, so probably quickly fixed when discovered.
> Anyway, if your mail server allow spoofed sender to deliver emails to
> local mailboxes i think you already have a problem.

Unfortunately, most email servers allow spoofed senders to deliver
emails to local mailboxes, because it's the way people use email in
practice. The only exception is when the sender has a published strict
DMARC policy and the recipient actually enforces it, which is a very
rare combo. And even more rare it is that the sender-SMTP verifies that
the user is allowed to use the From address it uses.

Seeing as this would be secure only in very specific cases, and it can
very much be implemented outside of `rss2email` (it can be a separate
process that hooks into the SMTP or IMAP server and just runs `r2e`
commands when a received email fits some requirements) and benefit other
use cases than `rss2email`, as it would allow running any (whitelisted)
command, I'm not sure this is something that has its space in
`rss2email`. But it does look interesting, especially if you are able to
give the security guarantees that make it secure!

**Comment by nikaro** [comment]
On Sun May 31, 2020 at 10:02 AM CEST, Léo Gaspard wrote:
> Unfortunately, most email servers allow spoofed senders to deliver
> emails to local mailboxes, because it's the way people use email in
> practice. The only exception is when the sender has a published strict
> DMARC policy and the recipient actually enforces it, which is a very
> rare combo. And even more rare it is that the sender-SMTP verifies that
> the user is allowed to use the From address it uses.

My mail server would not accept a mail from `@karolak.fr` it if did not
came from itself... i think.

> Seeing as this would be secure only in very specific cases, and it can
> very much be implemented outside of `rss2email` (it can be a separate
> process that hooks into the SMTP or IMAP server and just runs `r2e`
> commands when a received email fits some requirements) and benefit other
> use cases than `rss2email`, as it would allow running any (whitelisted)
> command, I'm not sure this is something that has its space in
> `rss2email`. But it does look interesting, especially if you are able to
> give the security guarantees that make it secure!

Ok no problem let's close this for now, until i eventually come with
something secure.

**Comment by Ekleog** [comment]
>> Unfortunately, most email servers allow spoofed senders to deliver
>> emails to local mailboxes, because it's the way people use email in
>> practice. The only exception is when the sender has a published strict
>> DMARC policy and the recipient actually enforces it, which is a very
>> rare combo. And even more rare it is that the sender-SMTP verifies that
>> the user is allowed to use the From address it uses.
>
> My mail server would not accept a mail from `@karolak.fr` it if did not
> came from itself... i think.

You can test by doing something like the following :)
```
$ nc smtp.karolak.fr 25
EHLO foo
MAIL FROM:<somebody@karolak.fr>
RCPT TO:<you@karolak.fr>
DATA
Subject: hello
Date: Sun, 31 May 2020 12:36:56 -0700

hello
.
QUIT
```

There are some subtleties for which headers exactly are required
depending on which mail server you use (here I've just set `Subject` and
`Date`, which usually are the only two required — you may want to add
`From:` and `To:` there), but unless you've specially configured your
mail server to reject mails from `@karolak.fr` that don't come from
itself I'd be willing to bet it's going to work ;)

(Also, this covers only the “envelope-from” spoofing, not the `From:`
header spoofing, which is even more rarely handled correctly — as you
initially wanted to filter on the `From:` address)

The reason why is, that most people don't know how to configure their
email client with one SMTP submission server per email address, and thus
end up having eg. their gmail and yahoo email addresses both using the
yahoo SMTP server. And then if gmail rejected emails to it that don't
come from it, such a client wouldn't be able to send mails to other
gmail users.

Some providers are the exception (actually the yahoo-gmail couple is the
major one in the domain, yahoo has a strict DMARC policy and gmail
enforces the DMARC policy), but the rule is, unfortunately (or
fortunately, depending on the point of view), that email spoofing is
still nowadays basically free-for-all, for user convenience reasons.

**Comment by auouymous** [comment]
> Seeing as this would be secure only in very specific cases, and it can very much be implemented outside of `rss2email` (it can be a separate process that hooks into the SMTP or IMAP server and just runs `r2e` commands when a received email fits some requirements) and benefit other use cases than `rss2email`, as it would allow running any (whitelisted) command, I'm not sure this is something that has its space in `rss2email`.

I agree with this, make it a separate program

It could be secured with public-private key encryption of the command. Use a special subject the server listens for, or a dedicated email address for commands. Then encrypt the command(s) in the body using the server's public key. It isn't that hard to configure an email client to encrypt the body when sending to a specific recipient. A shell script could also be used that encrypts $* and pipes it to `mail`, creating a command similar to `ssh <host> <command>`, but via email.

The server's key isn't actually "public" in this case, it MUST be treated like a password and not actually made public. It could have public-private keys per user along with an email address for each one. The email address is the username and the public key is the password. A system-wide service could map to real users and run the commands as them.

**Comment by nikaro** [comment]
On Sun May 31, 2020 at 5:15 PM CEST, Léo Gaspard wrote:
> You can test by doing something like the following :)
> ```
> $ nc smtp.karolak.fr 25
> EHLO foo
> MAIL FROM:<somebody@karolak.fr>
> RCPT TO:<you@karolak.fr>
> DATA
> Subject: hello
> Date: Sun, 31 May 2020 12:36:56 -0700
>
> hello
> .
> QUIT
> ```

For the record, it worked, though my spam filter flagged it. But i
suspect that it is only because i send it from home with an "home IP"
(ie. in RBL_SPAMHAUS_PBL). Will try again with a "clean IP".

I always though it would not allow unauthenticated emails from my
domain.

Thank you for the shared knowledge.
