### ISSUE TITLE
Cover rss2email by continuous integration?

### ISSUE THREAD

**Issue by hartwork** [rss2email/rss2email#12]
Hi!

I don't see any traces of something like Travis CI or so here yet. Are there plans to get that layer of protection against regressions?

Best, Sebastian

**Comment by Yannik** [comment]
@hartwork I think we'd like that, so please submit a PR if you can :)

**Comment by hartwork** [comment]
Hi!

If I'd find time we'd need someone to
- enable Travis CI including branches and pull requests for this very repository
- someone with permissions to merge pull requests to master.

Do you have permissions for both of these?

**Comment by Profpatsch** [comment]
I’m afraid @jsbackus didn’t give us any permissions to edit repository settings.

**Comment by Yannik** [comment]
@hartwork @Profpatsch and I can merge to master. I'll try to get travis-ci connected to repo.

**Comment by hartwork** [comment]
Interesting. I guess you'll keep me updated on how that goes.

**Comment by jsbackus** [comment]
Hi folks, sorry for taking so long to respond. travis-ci access has been granted, as mentioned in #32.

Glad to see all the activity!

**Comment by Yannik** [comment]
@jsbackus 
Nope, doesn't work:
"You don't have sufficient rights to enable this repo on Travis.
Please contact the admin to enable it or to receive admin rights yourself."

**Comment by hartwork** [comment]
![screenshot_20181218_152300_pull_requests](https://user-images.githubusercontent.com/1577132/50742840-7e583f00-1210-11e9-9368-b9b629baf05d.png)

@jsbackus this^^ is what it looks like with Expat:
