### ISSUE TITLE
Suggestion to add an option to send an email if RSS feed is down and/or there is some sort of error retrieving RSS

### ISSUE THREAD

**Issue by jaytrinitron** [rss2email/rss2email#121]
Would be a nice feature to have considering I don't know whether my custom feed just doesn't have any updates or my rss feed generator has stopped working without SSHing into my server itself. It's even more difficult when I am away from home as my server is not exposed to the open internet. Just think it would be helpful.

I'm still pretty new to Linux so if there is a other/better way to do what I am suggesting please let me know.

**Comment by auouymous** [comment]
r2e writes errors to stderr which causes cron to send an email. Are you not using cron or not checking mail on the user running cron?

**Comment by jaytrinitron** [comment]
I am using cron, I didn't know that was an option, just got it setup exactly how I want. Thank you so much!
