### ISSUE TITLE
Squarespace generated RSS feeds generate numerous/frequent blank messages.

### ISSUE THREAD

**Issue by jdwhite** [rss2email/rss2email#124]
Example URL: https://www.macsparky.com/blog?format=rss

Often triggers messages with blank subjects and bodies.

**Comment by auouymous** [comment]
I am unable to reproduce. Does removing the feed and re-adding it trigger the problem for any current entries?

**Comment by Ekleog** [comment]
@jdwhite Do you know of any current reproducer? If you see it happen again, can you fetch the RSS file and just copy-paste it someplace so that it'd be possible to investigate

**Comment by jdwhite** [comment]
Interestingly enough, about a week after I opened this issue I stopped seeing that behavior. I've been watching it the last few weeks and at this point I'm going to close it and call it temporary insanity on the part of Squarespace.

**Comment by Ekleog** [comment]
Cool, thank you for the feedback!
