### ISSUE TITLE
Embed pictures in the email

### ISSUE THREAD

**Issue by youknow10** [rss2email/rss2email#125]
Many RSS feeds have pictures in them. Such as https://xkcd.com/atom.xml
It would be great to embed these pictures in the email instead of leaving the link to the original website.
https://www.campaignmonitor.com/blog/email-marketing/2019/04/embedded-images-in-html-email/
Technically, it should be possible with the post-processing feature but I don't know how to do it.

**Comment by auouymous** [comment]
Try setting `html-mail = True` in the config file if you have an HTML capable MUA.

**Comment by Ekleog** [comment]
@youknow10 Seeing you didn't answer @auouymous's question, I'm closing this issue, assuming it solved your issue indeed. If that's not the case, feel free to reopen or ask for it to be reopened!

**Comment by willemml** [comment]
I came across this software and am wondering if having images embedded in emails is possible. I have `html-mail` set to `True` (I am using mu4e in GUI mode, using rss2email with `email-protocol = "maildir"`.)

**Comment by auouymous** [comment]
It should if your MUA supports HTML and the feed contains IMG tags in its description. However, automatically downloading files linked in an email has security and privacy issues and your MUA might either not allow it, or require you to explicitly enable it.

**Comment by amiryal** [comment]
The OP specifically (but indirectly, through a link to the article) talks about putting the burden of downloading the images and embedding them in messages (using either `data:` or `cid:` URIs) on r2e. Although it sounds like a nice feature to have (I would turn it on!), I think it is out of scope for r2e.
