### ISSUE TITLE
"looks like HTML" warning broken

### ISSUE THREAD

**Issue by jwilk** [rss2email/rss2email#160]
In `rss2email/feed.py` there's this code to warn when the server sent you HTML: 
```python
http_headers = parsed.get('headers', {})
...
    if 'html' in http_headers.get('content-type', 'rss'):
        _LOG.warning('looks like HTML: {}'.format(self))
        warned = True
```

But `http_headers` is a normal dict with keys that were *not* lower-cased. So this warning won't trigger most of the time.

(This was tested with rss2email 3.12.2 and feedparser 5.2.1.)

**Comment by Ekleog** [comment]
Thank you for the report! This should hopefully be fixed with #170 :)
