### ISSUE TITLE
Is starttls supported? Troubleshooting protonmail bridge setup.

### ISSUE THREAD

**Issue by adigitoleo** [rss2email/rss2email#162]
I'm having trouble setting up smtp for Protonmail Bridge. This stuff is pretty new to me so I might be premature in opening an issue, but it is working for ``git send-email`` and not for ``r2e run``.

Output from ``r2e run`` (same with ``verbose = debug``):

```
2021-01-21 14:21:32,341 [ERROR] could not connect to mail server 127.0.0.1
2021-01-21 14:21:32,342 [ERROR] cause: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)
2021-01-21 14:21:32,342 [ERROR] reason: WRONG_VERSION_NUMBER
```

Relevant config sections (didn't touch anything else yet):

```
to = <my protonmail address>
email-protocol = smtp
smtp-auth = True
smtp-username = <my protonmail address>
smtp-password = <key from Protonmail Bridge>
smtp-server = 127.0.0.1
smtp-port = <smtp port from Protonmail Bridge>
smtp-ssl = True

[feed.r2e]
url = https://github.com/rss2email/rss2email/commits.atom
```

The ``smtp-port`` is changed from it's default vaule. For comparison, this is from my ``.gitconfig``:

```
[sendemail]
    smtpServer = 127.0.0.1
    smtpServerPort = <smtp port from Protonmail Bridge>
    smtpUser = <my protonmail address>
    smtpPass = <key from Protonmail Bridge>
    smtpEncryption = starttls
```

The only difference I can see is the ``starttls`` instead of ``ssl``. In the Protonmail Bridge, there is an option to choose either ``ssl`` or ``starttls`` authentication. Does rss2email support ``starttls``? Or maybe there is something else I am missing here.

Output of ``openssl version`` is ``OpenSSL 1.1.1i  8 Dec 2020``. If I set ``smtp-ssl = False`` than protonmail can't authenticate.

**Comment by Ekleog** [comment]
Hello,

Sorry for not having answered earlier. If you're still interested in getting this working, could you give me the version of rss2email that you're using?

AFAIR rss2email should already be doing STARTTLS with the parameters you showed, so there's something weird here.

**Comment by adigitoleo** [comment]
@Ekleog Hey, no problem. I actually closed this since I moved away from using Protonmail for SMTP (too much hassle in my opinion).

For posterity: if anyone else is having trouble with Protonmail Bridge I suggest opening your own issue.

**Comment by Ekleog** [comment]
Cool, thank you for the feedback :)
