### ISSUE TITLE
could not connect to mail server smtp.gmail.com cause: server_hostname cannot be an empty string or start with a leading dot.

### ISSUE THREAD

**Issue by hista** [rss2email/rss2email#165]
Hi,
I'm facing an issue when I try to run r2e:

> r2e -V run
> could not connect to mail server smtp.gmail.com
> cause: server_hostname cannot be an empty string or start with a leading dot.
> check your config file to confirm that smtp-server and other mail server settings are configured properly

Could you please help me to fix it?
Here is my rss2email.cfg:

> [DEFAULT]
> from = me@mydomain.com
> use-8bit = False
> force-from = False
> use-publisher-email = False
> name-format = {feed-title}: {author}
> to = rss@mydomain.com
> proxy = 
> feed-timeout = 60
> active = True
> digest = False
> date-header = True
> date-header-order = modified, issued, created, expired
> bonus-header =
> trust-guid = True
> trust-link = False
> encodings = US-ASCII, ISO-8859-1, UTF-8, BIG5, ISO-2022-JP
> post-process = 
> digest-post-process = 
> html-mail = True
> use-css = False
> css = h1 {
>         font: 18pt Georgia, "Times New Roman";
>         }
>         body {
>         font: 12pt Arial;
>         }
>         a:link {
>         font: 12pt Arial;
>         font-weight: bold;
>         color: #0000cc;
>         }
>         blockquote {
>         font-family: monospace;
>         }
>         .header {
>         background: #e0ecff;
>         border-bottom: solid 4px #c3d9ff;
>         padding: 5px;
>         margin-top: 0px;
>         color: red;
>         }
>         .header a {
>         font-size: 20px;
>         text-decoration: none;
>         }
>         .footer {
>         background: #c3d9ff;
>         border-top: solid 4px #c3d9ff;
>         padding: 5px;
>         margin-bottom: 0px;
>         }
>         border: solid 4px #c3d9ff;
>         }
>         margin-left: 5px;
>         margin-right: 5px;
>         }
> unicode-snob = False
> links-after-each-paragraph = False
> body-width = 0
> email-protocol = smtp
> sendmail = /usr/sbin/sendmail
> smtp-auth = True
> smtp-username = me@mydomain.com
> smtp-password = password
> smtp-server = smtp.gmail.com:587
> smtp-ssl = True
> smtp-ssl-protocol = SSLv3
> imap-auth = False
> imap-username = username
> imap-password = password
> imap-server = imap.yourisp.net
> imap-port = 143
> imap-ssl = False
> imap-mailbox = INBOX
> verbose = warning

Thanks in advance for your kind help.

**Comment by auouymous** [comment]
Change
```
smtp-server = smtp.gmail.com:587
```
to
```
smtp-server = smtp.gmail.com
smtp-port = 587
```

**Comment by hista** [comment]
Thanks for your quick answer.
I did, but now it complains about this extra parameter:

> extra configuration key: smtp-port

**Comment by auouymous** [comment]
What version of r2e are you running?

**Comment by hista** [comment]
rss2email 3.9

**Comment by auouymous** [comment]
Can you update to 3.12.2?

**Comment by hista** [comment]
V3.9 is the last stable version for debian (https://packages.qa.debian.org/r/rss2email.html), but yes I can try to install the git version.

New issue:

> rss2email$ python setup.py install
>   File "setup.py", line 4
> SyntaxError: Non-ASCII character '\xc3' in file setup.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by auouymous** [comment]
Do you have python 2 installed? It is possible your default python is 2 and maybe `python3 setup.py install` will work. If that doesn't work you could try deleting line 4 from setup.py or maybe inserting `# -*- coding: utf-8 -*-` at the top.

The git version will require feedparser 6+ to be installed.

**Comment by hista** [comment]
`python3 setup.py install` did work indeed.
Now I'm having the last version: 

> r2e --version
> rss2email 3.12.1


But still blocked:

> 
> r2e -V run
> 2021-02-14 13:51:48,798 [ERROR] could not connect to mail server smtp.gmail.com
> 2021-02-14 13:51:48,804 [ERROR] cause: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1056)
> 2021-02-14 13:51:48,804 [WARNING] check your config file to confirm that smtp-server and other mail server settings are configured properly
> 2021-02-14 13:51:48,804 [ERROR] reason: WRONG_VERSION_NUMBER

Any idea?

**Comment by auouymous** [comment]
Try `smtp-ssl = False`, it will use starttls instead of ssl.

**Comment by hista** [comment]
It seems to work now!

Here is my config:

> smtp-auth = True
> smtp-username = myaddress@gmail.com
> smtp-password = mypassword
> smtp-server = smtp.gmail.com
> smtp-port = 587
> smtp-ssl = False

Thanks auouymous for your kind help and patience :)

**Comment by Ekleog** [comment]
I'm coming in late, but thank you for all the help! :D
