### ISSUE TITLE
[3.13|master] 5 tests fail with Python 3.9 (but not 3.7 or 3.8)

### ISSUE THREAD

**Issue by hartwork** [rss2email/rss2email#178]
5 tests seem to fail for Python 3.9 (but not 3.7. or 3.8) with both release 3.13 and Git `HEAD` on `master`:

```console
# cd "$(mktemp -d)"
# git clone --depth 1 https://github.com/rss2email/rss2email
# cd rss2email/
# git rev-parse HEAD
9a508aa0e0af37c749fcc4d3d446f49aecd2add9
# virtualenv --python=python3.9 venv
# source venv/bin/activate
# pip install setuptools .
# cd test/
# python --version
Python 3.9.2
# python -m unittest --verbose test_reply_changes.py
test_default (test_reply_changes.TestReplyChanges) ... FAIL
test_no_send (test_reply_changes.TestReplyChanges) ... FAIL
test_off (test_reply_changes.TestReplyChanges) ... FAIL
test_on (test_reply_changes.TestReplyChanges) ... FAIL
test_switch (test_reply_changes.TestReplyChanges) ... FAIL

======================================================================
FAIL: test_default (test_reply_changes.TestReplyChanges)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmp.mPUH6QldWF/rss2email/test/test_reply_changes.py", line 34, in test_default
    self.assertEqual(1, len(messages))
AssertionError: 1 != 0

======================================================================
FAIL: test_no_send (test_reply_changes.TestReplyChanges)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmp.mPUH6QldWF/rss2email/test/test_reply_changes.py", line 92, in test_no_send
    self.assertEqual(2, len(messages))
AssertionError: 2 != 0

======================================================================
FAIL: test_off (test_reply_changes.TestReplyChanges)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmp.mPUH6QldWF/rss2email/test/test_reply_changes.py", line 43, in test_off
    self.assertEqual(1, len(messages))
AssertionError: 1 != 0

======================================================================
FAIL: test_on (test_reply_changes.TestReplyChanges)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmp.mPUH6QldWF/rss2email/test/test_reply_changes.py", line 52, in test_on
    self.assertEqual(2, len(messages))
AssertionError: 2 != 0

======================================================================
FAIL: test_switch (test_reply_changes.TestReplyChanges)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmp.mPUH6QldWF/rss2email/test/test_reply_changes.py", line 76, in test_switch
    self.assertEqual(2, len(messages))
AssertionError: 2 != 0

----------------------------------------------------------------------
Ran 5 tests in 2.834s

FAILED (failures=5)
```

**Comment by Ekleog** [comment]
Hmm interesting, looks like we never CI'd on this file yet it never stopped working until 3.13.

@kaashif Was not running test_reply_changes.py on purpose, when you created the github action, or was it an oversight?

**Comment by hartwork** [comment]
The CI doesn't cover 3.9 — https://github.com/rss2email/rss2email/blob/420b65574a23c9526024669f2ee99c871fd5823e/.github/workflows/python-package.yml#L17 — that's why I think it didn't show. There are more places where 3.9 is missing, e.g. in `setup.py`.

**Comment by amiryal** [comment]
> Hmm interesting, looks like we never CI'd on this file yet it never stopped working until 3.13.

I ran a cursory test on v3.12.3 and it failed as well. The problem is that the return value from `urllib.request.urlopen` changed to now [always have the `status` attribute](https://docs.python.org/3.9/library/urllib.request.html#urllib.request.urlopen). This breaks the expectation of both feedparser internals and our `_check_for_errors` method, which both do `getattr(result, 'status', 200)`. In Python < 3.9 this used to return `200` for `file:` feeds, but now returns `None`.

> @kaashif Was not running test_reply_changes.py on purpose, when you created the github action, or was it an oversight?

Seems like either an oversight or a compromise after running into issues. Instead of executing `poetry run ./test/test.py -v` it should execute `cd ./test; poetry run python -m unittest`, as instructed in `test/README`.

> The CI doesn't cover 3.9

True, that’s yet another issue, but as @Ekleog pointed out, fixing it alone would not have revealed the regression in CI. ☹

If nobody beats me to it, I can try to submit a PR to fix all three issues, but that may not happen until next weekend.

**Comment by kaashif** [comment]
> Hmm interesting, looks like we never CI'd on this file yet it never stopped working until 3.13.
> 
> @kaashif Was not running test_reply_changes.py on purpose, when you created the github action, or was it an oversight?

It was an oversight, I didn't notice at the time that there even was another file with tests.
