### ISSUE TITLE
Stop `r2e run` from overwriting config file

### ISSUE THREAD

**Issue by duxovni** [rss2email/rss2email#185]
It looks like when `r2e run` calls `feeds.save()` to update the data file, it also rewrites the config file from scratch. I'm trying to write an Ansible playbook that (among other things) sets up rss2email with a configurable set of feeds, and when the config gets overwritten, it destroys the marker comments that help my playbook keep track of which feeds it's already added. In general it'd be nice if the config only got modified by operations that are supposed to change the configuration, like adding/removing/pausing feeds.

**Comment by amiryal** [comment]
See also https://github.com/rss2email/rss2email/issues/110.

**Comment by duxovni** [comment]
Oops, I searched a little but didn't run find that one.
