### ISSUE TITLE
Quick Update (new maintainers)

### ISSUE THREAD

**Issue by jsbackus** [rss2email/rss2email#19]
Hi folks,

I just wanted to give a quick update. I've been away a lot longer than I'd planned, and I really appreciate your patience. I have a lot of demands on my time and haven't been able to make any time for FOSS activities. My time is still going to be tightly constrained for the foreseeable future, but I will be able to make a little time for this project once we get into June. 

So, rough schedule:
* Early June: initial release using master branch
* Mid/late June: release dev branch + relevant fixes
* July: release next version

I apologize for disappearing for so long, and thanks again for your continued patience.

Thanks!
jeff

**Comment by Profpatsch** [comment]
An update: Jeff has added @Ekleog, @kaashif, @Yannik and myself to the `rss2email` organization, so we’ll hopefully be able to administrate the project with more manpower.

**Comment by Ekleog** [comment]
I suggest `#rss2email` on Freenode to try to coordinate discussion in a way less formal than GitHub.

**Comment by Ekleog** [comment]
It's been a while, let's close and unpin this :)
