### ISSUE TITLE
--config and --data are Unrecognised Arguments

### ISSUE THREAD

**Issue by LewisSpring** [rss2email/rss2email#191]
Hi there,
If I try to use --data or --config (or their -d and -c counterparts) I get a unrecognised arguments error message.
I've tried with or without quotations. Here's an example of the command I am running.
`/r2e # ./r2e new mail@email.domain -c "/r2edata/" -d "/r2edata/"
usage: rss2email [-h] [-v] [--full-version] [-c PATH] [-d PATH] [-V]{new,email,add,run,list,pause,unpause,delete,reset,opmlimport,opmlexport} ...
rss2email: error: unrecognized arguments: -c /r2edata/ -d /r2edata/`
Thanks!

**Comment by auouymous** [comment]
Which version are you using? I tried `r2e -d .foo -c .bar run` with 3.13.1 and it created `.foo`,  and ran without errors. I'm using #186 so not creating `.bar` was expected. The long options also worked.

One is issue is that `r2e -d .foo/ run` creates a `.foo` **file** instead of the directory I expected it to create.

**Comment by LewisSpring** [comment]
> Which version are you using? I tried `r2e -d .foo -c .bar run` with 3.13.1 and it created `.foo`, and ran without errors. I'm using #186 so not creating `.bar` was expected. The long options also worked.
> 
> One is issue is that `r2e -d .foo/ run` creates a `.foo` **file** instead of the directory I expected it to create.

I'm running 3.13.1, I downloaded it yesterday.

**Comment by LewisSpring** [comment]
Typically, another issue.
I've set email-protocol = SMTP and added my SMTP credentials and the like.
But If I run ./r2e run, I get sendmail errors.
Is there something I need to do to get r2e to read the configuration changes?

**Comment by auouymous** [comment]
Are you passing the -d and -c options so it uses your non-standard config and data files? Have you tried running it with -VVV for more verbosity? Are the smtp settings in [DEFAULT] section or in a feed's section?

**Comment by LewisSpring** [comment]
> Are you passing the -d and -c options so it uses your non-standard config and data files? Have you tried running it with -VVV for more verbosity? Are the smtp settings in [DEFAULT] section or in a feed's section?

Yes, I want the data and config files in the same directory as the R2E files.
Am I supposed to run "./r2e run -VVV"? Becuase -VVV or even just -V returns an unrecognised argument.

The SMTP are in the CONFIG file, under [DEFAULT].

**Comment by auouymous** [comment]
Use `r2e -c <your file> -d <your file> -VVV run`. You must always specify the -c and -d options so it can find them in the non-standard locations, I'd suggest setting up an alias or wrapper script to make it easier when manually running from console. The -c, -d and -VVV go before the command (run), while command specific options go after it (--clean and --no-send).

**Comment by LewisSpring** [comment]
> Use `r2e -c <your file> -d <your file> -VVV run`. You must always specify the -c and -d options so it can find them in the non-standard locations, I'd suggest setting up an alias or wrapper script to make it easier when manually running from console. The -c, -d and -VVV go before the command (run), while command specific options go after it (--clean and --no-send).

I understand now.
I think the from address was the issue
`2021-06-30 20:57:58,803 [DEBUG] no sender address found, fallback to default`
but now I've rewritten that line it seems to work!
Thanks!
I'll give it a while, see if I have any more issues.
