### ISSUE TITLE
id selectors in css are really config comments

### ISSUE THREAD

**Issue by squeakbat** [rss2email/rss2email#192]
The default css config value contains id selectors "#entry" and "#body" which are also config file comments.  Not only do they get ignored, they are dropped when the config file is written back.

So, the easy fix is to change them to something like "*#entry"` and "*#body".  However, I think they should be class selectors instead (with appropriate changes in the code), like .header and .footer.  I know this would be an incompatible change, but how many users actually write their own css?  (OK, I do.)

Being classes will also make it possible to implement a feature I want to add: digest as a single-part html message body.  Otherwise, they'll be duplicate ids.

**Comment by squeakbat** [comment]
I should have said I can submit a pull request, whatever is decided here.

**Comment by Ekleog** [comment]
Would it make sense to have them be both class and id attributes in the HTML, and to have the default css use class selectors?

This way we'd avoid the incompatible change, and I think this'd solve the main issue :)

**Comment by squeakbat** [comment]
Pull request #193 merged as commit 4a088c7efe1c76fa1ebe842adc8e2a796df8f313.
