### ISSUE TITLE
Update man page

### ISSUE THREAD

**Issue by jsbackus** [rss2email/rss2email#2]
Need to update man page with changes since @wking's master branch.

**Comment by Ekleog** [comment]
According to the changelog, we're missing `Add new `feed-name` and `feed-url` attributes for the `name-format` setting.` and `Allow multiple SMTP recipients` for the manpage.

**Comment by Profpatsch** [comment]
I started working on this a while ago: https://github.com/rss2email/rss2email/tree/man-overhaul

Still heavy WIP.
