### ISSUE TITLE
Emails still being sent

### ISSUE THREAD

**Issue by progkix** [rss2email/rss2email#20]
I was testing a couple of different configuration settings and I've got something messed up somewhere. Looking for a little help in determining what is wrong.

I setup r2e as a cron job to run every 6 hours. The last time it ran was yester at 1800 before I disabled it.

Something in my option testing has triggered r2e emails to continually be sent even though r2e is not being run. I've probably gotten 2000 emails since yesterday evening.

Any ideas what I might have hosed up? Need to look at anything? Ask for it and I'll send it along.

**Comment by jsbackus** [comment]
I've seen this before, but in my case it was the email server getting backed up / r2e exceeding a quota or SPAM throttling limit. Emails would slowly pour in in X-sized batches, where X was the throttling limit. A few questions:
1. r2e version?
1. Are these e-mails still coming in? 
1. Is the r2e process still running?

**Comment by progkix** [comment]
I'm getting about 6 every 5 minutes.

I just did an r2e reset followed by an r2e pause. my plan is to let it sit and see if they finally stop before taking the pause off.

r2e version: 3.9
email still coming in
r2e not running

**Comment by jsbackus** [comment]
Hmmm... In the past, have you received larger batches of e-mails via the e-mail server you are using now? Are the e-mails all the same or are they different?

**Comment by progkix** [comment]
Yes, yesterday evening it was almost a non-stop stream of emails - first time running rss2email.

Emails for the a particular feed appear to be the same but i can't tell for sure since they're spaced so far apart when sent. I'll have to remember to keep a selected one to check that.

**Comment by jsbackus** [comment]
Yeah, that was similar to my experience. It was like I overloaded things fiddling with the config file. Once the stream of e-mails stop:
1. Verify that you've received an e-mail for the latest entry for a given feed.
1. Run once (i.e. not via cron) and wait for e-mails to arrive. See if you get any repeats and see how long it takes for things to show up.

**Comment by progkix** [comment]
That's my plan - wait for the emails to stop and the do a manual run and verify what I get.

**Comment by jsbackus** [comment]
Sounds good!

**Comment by progkix** [comment]
Well, the emails have finally stopped. All told, I probably got 5000 over the course of 2 days.

I'm not sure exactly what the next step should be. I have the r2e cron job disabled and all the feeds are set to inactive.

Should I set them all back to active and the manually execute an r2e run --no-send to populate all the urls for each feed?

**Comment by jsbackus** [comment]
wow! That's quite a few.

Hmm.. Just enable 1 feed and manually run r2e to see if you get any duplicates. Maybe choose a field that hasn't been updated since you last run r2e.

**Comment by progkix** [comment]
I'm curious about some config options. I found this explanation of what they do from the URL below.

https://thomaslevine.com/scm/rss2email/vdiff?from=769b31607d3b63a3&to=f813fc6f43831a05&sbs=0&v

digest
    True: Send a single, multi-entry email per feed per rss2email run.
    False: Send a single email per entry.

trust-guid
    True: Receive one email per post.
    False: Receive an email every time a post changes.

trust-link
    True: Receive one email per unique link url.
    False: Defer to trust-guid preference.

    Toggling this for existing feeds may result in duplicates,
    because the old entries will not be recorded under their new
    link-based ids.

verbose
    Verbosity (one of 'error', 'warning', 'info', or 'debug').

**Comment by progkix** [comment]
It looks like I've got rss2email working properly now.

Just did a manual run and it only sent about 25 emails!

Woohoo!
