### ISSUE TITLE
Add support for storing config in a different dir

### ISSUE THREAD

**Issue by joeldeteves** [rss2email/rss2email#21]
Rather than storing the config in the user .config dir, it would be nice if we could specify which config to use when running the program, e.g. r2e -config /path/to/config

Alternatively, have 2 sets of config - one in a global location and then another in the user folder which overrides the global one.

Reason: This is useful for environments where we might want to run r2e on a server vs as a personal thing

**Comment by Profpatsch** [comment]
If I read the manpage correctly, `rss2email` has supported `--config` since `3.9` (somewhere in 2014).

**Comment by joeldeteves** [comment]
Thanks! I swear I read the manual but somehow I glossed over that!
