### ISSUE TITLE
[question] add opml file or monitor directory

### ISSUE THREAD

**Issue by GreenLunar** [rss2email/rss2email#212]
Hello, I didn't install nor have I tried rss2email yet.
Instead of individually [subscribing](https://github.com/rss2email/rss2email#using-rss2email) to feeds, is it possible to add an opml file or monitor a directory with ATOM/RSS files?

I'm asking this, because I'm scrapping data into Feeds and push them to a Feed Reader.
I rather scrape those pages into Feeds to be stored in a single News directory and push them to Email using rss2email.

If that's not possible, I'll just scrape the data into EML files, though I'll have to take care by myself to a mechanism that would detect data that was already downloaded, instead of relying the mechanism which is built into any Feed Reader.

**Comment by GreenLunar** [comment]
Is the following statement correct?
Upon impoering an OPML file, it would not appear in rss2email setting that an OPML was added, rather the settings would indicate the existance of the Feeds (those that were imported from the OPML file) just as it would when Feeds are being added individually.

To put this more simply:
Whether feeds A, B and C are added one by one, and whether by importing an OPML which has feeds A, B and C, the list of feeds would be presented in the setting of rss2email in the same way.

**Comment by auouymous** [comment]
Yes.

**Comment by GreenLunar** [comment]
Thank you.

Assumming all feeds are located under a single directory; and
Assuming rss2email has a database that indicates what feeds it already seen.

All is left to do is:
1) delete all feeds from rss2email (using rss2email or manually);
2) regenerate a new OPML file; and
3) adding the OPML file (using rss2email or manually - whatever way that will not effect the database depicted above);

If the above is incorrect in some way, please let me know.

Closing.

**Comment by auouymous** [comment]
Deleting feeds from r2e removes them from the config file AND from the data file. Assuming you have programmed something to scrape the feeds, you should have the ability to easily write a script to control r2e. Run r2e delete for any of `grep 'url' .config/rss2email.cfg |sed -E 's/.*file://'` paths no longer in your local filesystem. Then run r2e add for each file in the local filesystem, or filter them against the list of paths from the config file if r2e duplicates them.
