### ISSUE TITLE
Testing mail chain

### ISSUE THREAD

**Issue by edegraaff** [rss2email/rss2email#214]
Hi, i am rebuilding my pi with rss2email running bullseye. 
I installed exim4 and tested to send mail to my hosting proviers with authentication. 
Sending mail by the mail command did result in a delivered mail in my mailbox.

Running r2e run seem not to generate mails or are not been distributed by exim4
when i look in the config there is  an executable file in /usr/sbin/sendmail (it seems a exim )
root@nms:/home/pi# /usr/sbin/sendmail
Exim is a Mail Transfer Agent. It is normally called by Mail User Agents,
not directly from a shell command line. Options and/or arguments control
what it does when called. For a list of options, see the Exim documentation.

The question is:  does this emulate traditional sendmail and should there be an email in the exim maillog when r2e runns...??

And, is there a trick i can use to create testmails with r2e and have some debug entrys to check? 

Regards

Eelco

**Comment by auouymous** [comment]
Sorry for the late reply. Exim should be compatible, did you set the `to` option in r2e to a valid local user or remote email address? You can try `r2e -VVV run <feedname>` to show debug info while fetching a feed (preferrably with very few entries in case it works). You will need to delete and re-add the feed between runs, otherwise it will only send entries newer than the last fetch.

**Comment by edegraaff** [comment]
Hi, in the to field it is a valid email adress, and i had it working on my old pi, strange enough the only thing that has been changed is the os version it is now bullseye.
The rest of the install and the config has stayed the same
I will run the r2e -VVV run <feedname> and see if it will deliver a bit more info. 
It looks like the authentication to be able to send the mail is not working correctly. 
Here is one issue with exim i have found some info on and thats this line: 
TLS session: (certificate verification failed): delivering unencrypted to H=mail.tri-angle.nl [185.94.230.246] (not in hosts_require_tls)


Sending testmails from the command line with the mail command work , thats puzzeling me.

**Comment by auouymous** [comment]
There is no authentication or encryption with sendmail. r2e invokes the sendmail process and it should write a file to a queue, which is then read by the exim service to deliver it. That delivery process is failing because mail.tri-angle.nl either doesn't support encryption, and you are forcing it, or your setup only encrypts for certain hosts. Are you relaying all mail through mail.tri-angle.nl or sending directly to each recipient? You might want to fix that encryption issue in exim if relaying.

Are you sending with the mail command to the same address in r2e's `to` setting?

You could try stopping exim, sending mail with the mail command and r2e, and then examining the two queued files. Or setup a ~/.forward to another local user and read that user's /var/spool/mail/ file.

**Comment by edegraaff** [comment]
Thanks for helping me out, all mail should be accepted by mail.tri-angle.nl this is the mailserver that is hosted by an hosting provider, the settings there i have no influence on. The pi with exim is sending all mail to this mail server. The setting in exim is there is a smarthost for delivering all mail to mail.tri-angle.nl and exim is confgured to send mail with authentication to the smarthost otherwise the hosting provider wont accept the mail.

exim does process the mail for two different account settings i made them now similar

do i understand you well: 
the mail transfer will be done without exim by rrs2mail by the pyton script? 

i will also check the spool file later today

**Comment by auouymous** [comment]
> exim is confgured to send mail with authentication to the smarthost

That is a relay and how most people do it. Is `force-from` set to `True`, and the `from` setting in r2e configured to your email address at mail.tri-angle.nl? Many hosts won't relay mail with forged from addresses.

>  the mail transfer will be done without exim by rrs2mail by the pyton script?

No, r2e calls sendmail which writes a file to a local directory, and both exit, nothing is sent over the network. Then exim wakes up, processes the file and sends it over the network, or to another local user on the machine.

**Comment by edegraaff** [comment]
> > exim is confgured to send mail with authentication to the smarthost
> 
> That is a relay and how most people do it. Is `force-from` set to `True`, and the `from` setting in r2e configured to your email > address at mail.tri-angle.nl? Many hosts won't relay mail with forged from addresses.
Yes both set 

> 
> > the mail transfer will be done without exim by rrs2mail by the pyton script?
> 
> No, r2e calls sendmail which writes a file to a local directory, and both exit, nothing is sent over the network. Then exim 
> wakes up, processes the file and sends it over the network, or to another local user on the machine.
Thanks explaining

It seems i got it working again...  
>> You will need to delete and re-add the feed between runs, otherwise it will only send entries newer than the last fetch.
Should i take any action based on this received log file? 

2022-04-24 13:00:07,421 [INFO] refreshing feed ncsc (https://advisories.ncsc.nl/rss/advisories -> [XXXX@tri-angle.nl](mailto:XXXX@tri-angle.nl))
2022-04-24 13:00:07,423 [INFO] fetch ncsc (https://advisories.ncsc.nl/rss/advisories -> [XXXX@tri-angle.nl](mailto:XXX@tri-angle.nl))
2022-04-24 13:00:08,065 [INFO] process ncsc (https://advisories.ncsc.nl/rss/advisories -> [XXXX@tri-angle.nl](mailto:XXXX@tri-angle.nl))
2022-04-24 13:00:08,080 [INFO] refreshing feed secnl (https://www.security.nl/rss/headlines.xml -> [XXXX@tri-angle.nl](mailto:XXXX@tri-angle.nl))
2022-04-24 13:00:08,082 [INFO] fetch secnl (https://www.security.nl/rss/headlines.xml -> [XXXX@tri-angle.nl](mailto:XXXX@tri-angle.nl))
2022-04-24 13:00:08,821 [INFO] process secnl (https://www.security.nl/rss/headlines.xml -> [XXXX@tri-angle.nl](mailto:XXXX@tri-angle.nl))

?

**Comment by auouymous** [comment]
Good to hear. Did you have a question about that output?

**Comment by edegraaff** [comment]
> Good to hear. Did you have a question about that output?

Yes, how to switch off?  it is not the crontab that is making those emails as far as i can see?

**Comment by auouymous** [comment]
Set `verbose` to `warning` or `error` in the config file, it defaults to `info`. I use error, and one day a week cron runs r2e with --clean and -V to show warnings.

```
# Verbosity (one of 'error', 'warning', 'info', or 'debug')
```

**Comment by edegraaff** [comment]
> Set `verbose` to `warning` or `error` in the config file, it defaults to `info`. I use error, and one day a week cron runs r2e with --clean and -V to show warnings.
> 
> ```
> # Verbosity (one of 'error', 'warning', 'info', or 'debug')
> ```
ok it was indeed on info chaned to error , is there a seperate cron job, or should i add an extra with 
/usr/local/bin/r2e run --clean -V  also on a week base to get some info back in my logs?

**Comment by auouymous** [comment]
I have two cron entries.

```
00 17 * * 0 r2e -V run --clean
00 17 * * 1-6 r2e run
```

**Comment by edegraaff** [comment]
> I have two cron entries.
> 
> ```
> 00 17 * * 0 r2e -V run --clean
> 00 17 * * 1-6 r2e run
> ```

Clear, thanks will add the second one
