### ISSUE TITLE
Do a new release and update the links in the the PyPI page

### ISSUE THREAD

**Issue by Ekleog** [rss2email/rss2email#22]
rss2email currently has known bugs that have been fixed for 3 years but never released (for instance, https://github.com/wking/rss2email/issues/109 that's hitting me).

In order to distributions to be able to legitimately bump their rss2email packages, could you do a release (and also update the links on https://pypi.org/project/rss2email/ to point to the organization repository)?

Thank you for having taken over rss2email! and remember no one is eternal, it may be a good idea to add someone else to the organization, if you know of another high-volume contributor :)

**Comment by jsbackus** [comment]
Hi @Ekleog,

Unfortunately, work hasn't left me any time for F/OSS activities so I've had to step away.

Yes, we are definitely limited in what we can take on :smile:. I'm happy to add anyone to the organization who wants to progress the project. Anyone wanting to take on publishing releases to PyPi should e-mail me directly with their PyPi username.

Thanks again for your interest!

**Comment by Ekleog** [comment]
Closing as it has been superseded by https://github.com/rss2email/rss2email/issues/28 and the 3.10 milestone.
