### ISSUE TITLE
Errors after python update 

### ISSUE THREAD

**Issue by pdkrocul** [rss2email/rss2email#225]
I updated to Python 3.10.7 because of another tool

Now, I get

r2e --version
Traceback (most recent call last):
  File "/usr/bin/r2e", line 3, in <module>
    import rss2email.main
  File "/usr/lib/python3/dist-packages/rss2email/main.py", line 27, in <module>
    from . import command as _command
  File "/usr/lib/python3/dist-packages/rss2email/command.py", line 26, in <module>
    from . import error as _error
  File "/usr/lib/python3/dist-packages/rss2email/error.py", line 27, in <module>
    import feedparser as _feedparser
  File "/usr/lib/python3/dist-packages/feedparser.py", line 93, in <module>
    _base64decode = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'

Ideas?

**Comment by auouymous** [comment]
You are using a pre-6.0 version of feedparser which means you are also using an older version of rss2email. Try upgrading both, becuse the crash is coming from feedparser, not rss2email.

**Comment by pdkrocul** [comment]
I'm getting error messages about Python 2.7 when I run pip. I know this isn't rss2email related, but I'm in a Python 2/3 mess. Any ideas. I tried to remove Python 2 and I got warnings that it was a bad idea.

**Comment by auouymous** [comment]
I don't have pip installed and have never used it. Maybe someone else could help if you posted the errors.

**Comment by amiryal** [comment]
It is unfortunately hard to remote-troubleshoot like this. A few basic details might help, like which OS, how Python 2 was installed, how rss2email was installed, how Python 3 was installed/updated, etc., but I can’t promise anything.

Personally, I install rss2email using [pipx](https://pypa.github.io/pipx/). The pipx homepage includes instructions for `brew install pipx` and `python3 -m pip install --user pipx`, but I found that `sudo apt install pipx` works for me. Once you get pipx installed and working, `pipx install rss2email` should get you a working `r2e` again.
