### ISSUE TITLE
303 HTTP status issue

### ISSUE THREAD

**Issue by arunpersaud** [rss2email/rss2email#229]
When using rss2email on https://www.nature.com/nphys.rss I'm getting HTTP 303 errors. Feedparser seems to handle getting the feed content OK, but feed.py raises an error. I'm wondering if this [line](https://github.com/rss2email/rss2email/blob/7c1a2e1d705661c2de0982a5c4c7e6b0e657bf1e/rss2email/feed.py#L414)  should be changed to also exclude 303 status.

Happy to create a PR if needed.

**Comment by amiryal** [comment]
> I'm wondering if this [line](https://github.com/rss2email/rss2email/blob/7c1a2e1d705661c2de0982a5c4c7e6b0e657bf1e/rss2email/feed.py#L414) should be changed to also exclude 303 status.

Correct! But I would take it a step further and exclude all codes below 400 wholesale.

This line you have mentioned is part of a wider code section that, if I read correctly, tries to update the feed configuration with permanent redirects:
https://github.com/rss2email/rss2email/blob/7c1a2e1d705661c2de0982a5c4c7e6b0e657bf1e/rss2email/feed.py#L410-L415
Ignoring the fact that I dislike r2e’s tendency to overwrite the configuration file, I think (after doing [some reading](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_redirection)) that only 301 and 308 should get the special treatment, and all other status numbers should not be spelled out explicitly:
```python
        if status in [301, 308]:
            _LOG.info('redirect {} from {} to {}'.format(
                    self.name, self.url, parsed['url']))
            self.url = parsed['url']
        elif status >= 400:
            raise _error.HTTPError(status=status, feed=self)
```

**Comment by auouymous** [comment]
I agree with that change.

**Comment by arunpersaud** [comment]
I just wanted to check in what the status is. Still getting the same errors (and applying the above fix manually which seems to work). Anything I can help to get this merged? Thanks
