### ISSUE TITLE
doc update

### ISSUE THREAD

**Issue by edegraaff** [rss2email/rss2email#231]
git clone https://github.com/rss2email/rss2email.git

in the doc it is http and is no longer running

**Comment by auouymous** [comment]
Are you referring to the `$ git clone git://github.com/rss2email/rss2email.git` on https://github.com/rss2email/rss2email/blob/master/README.rst, or something else?

**Comment by edegraaff** [comment]
> 

yes it seems at least at my pi this seems not to work
git clone git://github.com/rss2email/rss2email.git
 but this does
git clone https://github.com/rss2email/rss2email.git
