### ISSUE TITLE
Can't include ampersand in URL querystring

### ISSUE THREAD

**Issue by blacknell** [rss2email/rss2email#238]
I'm trying to add this URL but it's stripping off the last parameter. I've tried wrapping it with `'"` but doesn't work

```
r2e add rpilocator https://rpilocator.com/?country=UK&cat=PI4
```
`r2e list` results in removing the `cat` querystring arg
> `0: [*] rpilocator (https://rpilocator.com/?country=UK -> redacted@mydomain.co.uk)`

```
r2e add rpilocator r2e add rpilocator 'https://rpilocator.com/?country=UK&cat=PI4'
```
`r2e list` appears to show success
> `0: [*] rpilocator (https://rpilocator.com/?country=UK&cat=PI4 -> redacted@mydomain.co.uk)
`

But `r2e run` results in removing the cat querystring
> `2023-04-26 10:32:44,620 [ERROR] sax parsing error: <unknown>:3:0: syntax error: rpilocator (https://rpilocator.com/?country=UK&cat=PI4 -> redacted@mydomain.co.uk)`

I've also tried escaping with `\&` and `%26` but I get similar parsing errors. Likewise with manually editing `rss2email.cfg`

**Comment by blacknell** [comment]
My typo - I'e updated above to show the feed URL's which is what I was actually trying based around the https://rpilocator.com/feed/?country=UK&cat=PI4

**Comment by amiryal** [comment]
> Shouldn't it warn if the saved URL is not the same as the one added

The shell interprets the `&` as a control operator and runs `r2e` in the background. `r2e` never gets a chance to see what was written after the `&`, because the shell interprets it as the next command to run, so there is no way for it to issue a warning message. :shrug:

**Comment by xrat** [comment]
@blacknell wrote: "Likwise with manually editing rss2email.cfg". Something else must be going on. @blacknell I use Links with `&`, they are listed in rss2email.cfg as plain `&`. They definitely work. What's your environment?

**Comment by blacknell** [comment]
I'm running it in Debian on a Pi

**Comment by xrat** [comment]
```
$ r2e --full-version
rss2email 3.14
python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
feedparser 6.0.10
html2text (2020, 1, 16)
$ cat /etc/debian_version 
11.6
$ r2e list | grep -cF '&'
21
$ r2e list | grep -cF '&amp;'
1
```

**Comment by blacknell** [comment]
```
$ r2e --full-version
rss2email 3.12.2
python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
feedparser 5.2.1
html2text (2020, 1, 16)
$ cat /etc/debian_version
11.6
$ r2e list | grep -cF '&'
1
$ r2e list | grep -cF '&amp;'
0
```

**Comment by auouymous** [comment]
> 2023-04-26 10:32:44,620 [ERROR] sax parsing error: <unknown>:3:0: syntax error: rpilocator (https://rpilocator.com/feed/?country=UK&cat=PI4 -> redacted@mydomain.co.uk)

That `r2e run` error isn't an issue with the URL, it is the parsing of the feed.

> rss2email 3.12.2
> feedparser 5.2.1

The taxo namespace used by that feed is 404 and maybe that causes issues in feedparser 5.2.1 or rss2email 3.12.2. Could you try updating to feedparser 6.0.10 and rss2email 3.14?
