### ISSUE TITLE
Render MathML as AsciiMath or LaTeX in text-only mode?

### ISSUE THREAD

**Issue by jeffkaufman** [rss2email/rss2email#242]
If an rss feed includes `<math>...</math>` rss2email in text-only mode strips out the tags.  So:

```
<math>
<msup>
  <mi>e</mi>
  <mrow>
    <mo>-</mo>
    <mn>7</mn>
    <mi>t</mi>
  </mrow>
</msup>
</math>
```

Goes through as:

```
e - 7 t
```

One way to make this better would be to run MathML through something like py_asciimath and emit:

```
e^(-7t)
```

Or

```
e^{-7t}
```

**Comment by auouymous** [comment]
rss2email uses html2text to strip the tags, and this might be better for them to implement. Unless py_asciimath can find and convert the tags before html2text strips them.

**Comment by jeffkaufman** [comment]
Thanks! Tracking this at https://github.com/Alir3z4/html2text/issues/336#issuecomment-1735550190
