### ISSUE TITLE
Can't find rss2email

### ISSUE THREAD

**Issue by bcosell** [rss2email/rss2email#246]
rss2email has stopped working [this on Linux] and I can't figure out why, so I thought I'd try reinstalling it  But when I go to "releases" I get 
"There aren’t any releases here"
How can I reinstall it?

**Comment by amiryal** [comment]
Right, the README is possibly outdated by a Github interface change. From the releases page, click on Tags:

![image](https://github.com/rss2email/rss2email/assets/105565/58437d5a-b050-44bd-a6aa-75a105762f96)

The right URL is: https://github.com/rss2email/rss2email/tags

**Comment by amiryal** [comment]
I am surprised that `pip install rss2email` is not mentioned anywhere in the README.
