### ISSUE TITLE
No mails received

### ISSUE THREAD

**Issue by stevenbaert** [rss2email/rss2email#247]
Love the project! However, trying now for some time to make it work. All RSS feeds are properly loaded, get no errors but neither any email. Is there logging (to be enabled) to understand what is going on?
Thanks for your feedback!

--- logs
2023-10-19 22:47:13,936 [INFO] refreshing feed goa (http://feeds.feedburner.com/blogspot/gJZg -> mymailaddress@gmail.com)
2023-10-19 22:47:13,936 [INFO] fetch goa (http://feeds.feedburner.com/blogspot/gJZg -> mymailaddress@gmail.com)
2023-10-19 22:47:14,514 [INFO] process goa (http://feeds.feedburner.com/blogspot/gJZg -> mymailaddress@gmail.com)
2023-10-19 22:47:14,519 [INFO] send message for goa (http://feeds.feedburner.com/blogspot/gJZg -> mymailaddress@gmail.com)
2023-10-19 22:47:14,549 [INFO] send message for goa (http://feeds.feedburner.com/blogspot/gJZg -> mymailaddress@gmail.com)
2023-10-19 22:47:14,574 [INFO] send message for goa (http://feeds.feedburner.com/blogspot/gJZg -> mymailaddress@gmail.com)
...

**Comment by auouymous** [comment]
Do you have the mail server configured properly in rss2email.cfg? And do you have access to the mail server logs?

**Comment by stevenbaert** [comment]
Thanks for your input. I have configured it as below (the relevant part as far as I know):

sendmail = /usr/sbin/sendmail
sendmail_config = 
smtp-auth = True
smtp-username = mymailaddress@gmail.com
smtp-password = mypassword
smtp-server = smtp.gmail.com
smtp-port = 587
smtp-ssl = True

Not sure why I would need the mail server logs. It would make much more sense to see the script itself throwing out the errors it has when sending.

**Comment by auouymous** [comment]
Is `email-protocol` set to `smtp`?

Mail server logs are only needed if sending to your own local smtp or sendmail server, which might not have handled the mails properly and r2e would have no errors to show.

**Comment by stevenbaert** [comment]
Thanks for prompt reply! Yes it is. Wrote a script to test everything is working fine and it is <see below, received that mail>.
I'm so suprised that there aren't any errors when I run r2e, isn't there a place where I can set verbose logging to understand what is happening?
---

import os                                                                                                                                                
import smtplib                                                                                                                                           
from email.message import EmailMessage                                                                                                                   
                                                                                                                                                        
# setup smtp configurations                                                                                                                              
SMTP_SERVER = 'smtp.gmail.com'                                                                                                                           
SMTP_PORT = 587                                                                                                                                          
SMTP_USERNAME = 'mymail@gmail.com'                                                                                                                 
SMTP_PASSWORD = 'mypssword'                                                                                                                       
                                                                                                                                                        
# setup email message                                                                                                                                    
msg = EmailMessage()                                                                                                                                     
msg['Subject'] = 'Test email from sendmail'                                                                                                              
msg['From'] = SMTP_USERNAME                                                                                                                              
msg['To'] = SMTP_USERNAME                                                                                                                                
msg.set_content('This is a test email sent from a script')                                                                                               
                                                                                                                                                        
# sending the mail                                                                                                                                       
server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)                                                                                                            
server.ehlo()                                                                                                                                            
server.starttls()                                                                                                                                        
server.login(SMTP_USERNAME, SMTP_PASSWORD)                                                                                                               
server.send_message(msg)                                                                                                                                 
                                                                                                                                                        
# close the smtp server                                                                                                                                  
server.quit()                                                                                                                                            
                                                                                                                                                        
print('Test email sent!')

**Comment by auouymous** [comment]
There is `r2e -VVV run` to get verbose output.

**Comment by stevenbaert** [comment]
Thanks, just a quick question: what would be the best way to test?
Now I'm adding extra feeds then run r2e again, but just would like to run a test with existing once.

**Comment by stevenbaert** [comment]
> There is `r2e -VVV run` to get verbose output.

That's really helpfull!

2023-10-20 11:23:55,584 [DEBUG] feed version rss20
2023-10-20 11:23:55,584 [DEBUG] processing https://blogs.nvidia.com/?p=67324
2023-10-20 11:23:55,584 [DEBUG] not seen https://blogs.nvidia.com/?p=67324
2023-10-20 11:23:55,584 [DEBUG] no sender address found, fallback to default
2023-10-20 11:23:55,588 [DEBUG] new message: A Mine-Blowing Breakthrough: Open-Ended AI Agent Voyager Autonomously Plays ‘Minecraft’
2023-10-20 11:23:55,588 [INFO] send message for nvidiablog (http://feeds.feedburner.com/nvidiablog -> mymailaddress@gmail.com)
2023-10-20 11:23:55,588 [DEBUG] sending message to mymailaddress@gmail.com via smtp.gmail.com
2023-10-20 11:23:55,658 [ERROR] could not connect to mail server smtp.gmail.com
2023-10-20 11:23:55,658 [ERROR] cause: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)
2023-10-20 11:23:55,658 [WARNING] check your config file to confirm that smtp-server and other mail server settings are configured properly
2023-10-20 11:23:55,658 [ERROR] reason: WRONG_VERSION_NUMBER

**Comment by stevenbaert** [comment]
Note that I have my from filled in and config seems also fine in rss2email.cfg (posted that). It seems as if it doesn't read from the cfg file then(?)

**Comment by auouymous** [comment]
Are you running r2e on a machine with old Python or openssl?

**Comment by stevenbaert** [comment]
Doesn't look like it

Python 3.11.5
>>> import ssl
>>> print(ssl.OPENSSL_VERSION)
OpenSSL 3.1.3 19 Sep 2023

**Comment by auouymous** [comment]
```
 smtp-ssl = True
```

Your test code didn't use SSL, try changing that setting to False.

**Comment by stevenbaert** [comment]
I will right away. Question though: how do I quickly test without the need to add an RSS feed each time?
Without new RSS feed, it will say there are no new feeds so won't send mails. I now have to add new RSS and I'm pretty much through all RSS feed I want to follow :-)

**Comment by stevenbaert** [comment]
> ```
>  smtp-ssl = True
> ```
> 
> Your test code didn't use SSL, try changing that setting to False.

Worked, awesome, thanks!!!

**Comment by auouymous** [comment]
Removing the feed and re-adding is probably the only way to re-send emails.

**Comment by stevenbaert** [comment]
> Removing the feed and re-adding is probably the only way to re-send emails.

Ok, just removed a line in xml works also to send one mail. I now can finetune further.
Looks great. Any suggestions/jump start tips welcome :-) I will use the readme as guide for testing.

Might also drop the full script in ChatGPT Advanced Analytics and ask for optimization suggestions in the code. If that would give valuable outcome, I certainly will give input!

**Comment by stevenbaert** [comment]
One more thing, I'd like to create a development and production version of RSS2email. So I can schedule the PRD version and meanwhile play around with the DEV version and other smtp config(s)
---
Can I have multiple config files for that on the same system?
So if I would copy paste the folder, setup another conda/virtual Python environment, do a git clone again and re-setup with r2e new you@yourdomain.com --config ./rss2config and —data ./rss2email.json that would work, right?

Just don't want to mess up my current (working) config :-)

**Comment by auouymous** [comment]
Yes, --config and --data allow alternate setups to be run as the same user. 

> Any suggestions/jump start tips welcome

Set verbose to error in config and use `r2e -V run --clean` once a week. That way you only see the "noise" from flaky feeds once a week. Look up --clean in the man page.
