### ISSUE TITLE
Making a custom Post Processor

### ISSUE THREAD

**Issue by LewisSpring** [rss2email/rss2email#249]
Hello,
I've been trying to set up a custom post processor to filter an incoming RSS Feed.

It's as simple as:
```
import rss2email.email

def process(feed, parsed, entry, guid, message):
    if feed == "daynews":
      if "daynews edition" in message.lower():
        return message
      else:
        return False
```

I cannot work out how to tell R2E to use this script as a post processor, I've tried putting it everywhere and always get a module not found error.

Please can you provide some guidance on how to set this up?

Thanks!

**Comment by auouymous** [comment]
The script must be in one of the directories listed by `python -c 'import sys ; print(sys.path)'`, or current directory. You can also set the PYTHONPATH environment variable to point to the script's directory.
