### ISSUE TITLE
New repository description

### ISSUE THREAD

**Issue by Profpatsch** [rss2email/rss2email#26]
We need a repository description.

`wking/rss2email` has the description

> open-source tool for Windows, Mac OS and UNIX for getting news from RSS feeds in email http://pypi.python.org/pypi/rss2email/

I’d leave out the distro-part and add “community maintained”.

Something like:

> Forward RSS feeds to your email address, community-maintained fork http://pypi.python.org/pypi/rss2email/

**Comment by xrat** [comment]
http://pypi.python.org forwards to https://pypi.python.org by means of a HTTP 301 ("moved permanently"). This then is redirected to https://pypi.org/project/rss2email/ , again by means of a HTTP 301. I suggest using either of the https links.

Also, should it be "community-maintained fork __of__ https://pypi.org/project/rss2email/"?

**Comment by Yannik** [comment]
I'd skip the "fork of" part.

**Comment by Profpatsch** [comment]
Okay, the new description is:

```
Forward RSS feeds to your email address, community maintained
https://pypi.org/project/rss2email/
```
