### ISSUE TITLE
Move to semver

### ISSUE THREAD

**Issue by Profpatsch** [rss2email/rss2email#27]
Simple change, but we should consider adding a third field to indicate non-breaking changes.

The last version was `3.9`, the next version is going to be `3.10.0` accordingly. If we fix a bug but don’t change the program’s interface, we increase to `3.10.1` instead of `3.11`. If something major is rewritten (or e.g. the database backend changes in a major way) we increase to `4.0`.

**Comment by Yannik** [comment]
agreed.

**Comment by Ekleog** [comment]
As I think everyone agrees on this, let's close :)
