### ISSUE TITLE
Update pypi

### ISSUE THREAD

**Issue by jsbackus** [rss2email/rss2email#3]
See @anarcat's suggestions from linkcheck/linkchecker#4 and wking/rss2email#97. We may need to create an alternate project if we can't recover the original.

**Comment by anarcat** [comment]
note that the new Warehouse deployment on PyPI.org may have different rules that could work around the issues we have with abandoned software. see:

https://pypi.org/help/#project-name-claim

there's [PEP-0541](https://www.python.org/dev/peps/pep-0541/) under way to fix this, apparently.

**Comment by wking** [comment]
I just made @jsbackus (PGP key 2B1A5ED6) an owner of the rss2email PyPI
package.  Feel free to delegate and pass that around as you see fit.

Sorry that took me so long :/.

**Comment by jsbackus** [comment]
@wking Thanks! No worries - I'm behind the ball myself. 😁

**Comment by hartwork** [comment]
Neither https://pypi.python.org/pypi/rss2email not http://www.allthingsrss.com/rss2email/ point to this repository, yet. Would be awesome to get that fixed so people don't need to find things like https://github.com/wking/rss2email/issues/97 to get an answer to where to go to for the latest. Thanks!

**Comment by Ekleog** [comment]
Closing as the exact remaining task has been extracted to https://github.com/rss2email/rss2email/issues/28
