### ISSUE TITLE
Sift through pulls on wking’s repository

### ISSUE THREAD

**Issue by Profpatsch** [rss2email/rss2email#40]
Go through https://github.com/wking/rss2email/pulls and integrate all pull requests that seem useful into this repository.

**Comment by Ekleog** [comment]
PRs still to be handled:
- [ ] https://github.com/wking/rss2email/pull/15
- [x] https://github.com/wking/rss2email/pull/21 (merged)
- [x] https://github.com/wking/rss2email/pull/32 (merged and duplicated at https://github.com/wking/rss2email/pull/76)
- [ ] https://github.com/wking/rss2email/pull/42
- [ ] https://github.com/wking/rss2email/pull/56
- [ ] https://github.com/wking/rss2email/pull/59
- [x] https://github.com/wking/rss2email/pull/72 (merged)
- [ ] https://github.com/wking/rss2email/pull/76
- [x] https://github.com/wking/rss2email/pull/78 (merged)
- [x] https://github.com/wking/rss2email/pull/82 (merged)
- [x] https://github.com/wking/rss2email/pull/85 (merged)
- [x] https://github.com/wking/rss2email/pull/86 (merged)
- [x] https://github.com/wking/rss2email/pull/87 (merged)
- [x] https://github.com/wking/rss2email/pull/89 (merged)
- [x] https://github.com/wking/rss2email/pull/95 (merged)
- [x] https://github.com/wking/rss2email/pull/100 (merged)
- [x] https://github.com/wking/rss2email/pull/101 (merged)
- [x] https://github.com/wking/rss2email/pull/106 (merged)
- [ ] https://github.com/wking/rss2email/pull/112

**Comment by Ekleog** [comment]
@Profpatsch I think this is ready to close, can you check the message above and verify that you agree with me about the PRs that are still heavily WIP? :)

**Comment by Profpatsch** [comment]
looks good to me.
