### ISSUE TITLE
Set the `Date` field of the email to the `pubDate` of the RSS feed

### ISSUE THREAD

**Issue by Ekleog** [rss2email/rss2email#47]
Everything is in the title, it'd help figuring out which item is newest when `rss2email` hasn't run for a long time and lots of items come up.

**Comment by nikaro** [comment]
Is this issue still relevant? I can see that there `date-header` config option.

**Comment by Ekleog** [comment]
It probably is not indeed, let's close for now and reopen if that was the wrong assessment.

Thank you for poking in here!
