### ISSUE TITLE
Add db cleanup feature to prevent heavy databases

### ISSUE THREAD

**Issue by sciunto** [rss2email/rss2email#49]
Hi,

I reported in the former project that I remarked that json db tends to grow significantly. (Original issue: https://github.com/wking/rss2email/issues/33). I experienced that it slows down quite heavily the run command.

I proposed a workaround here: https://github.com/wking/rss2email/pull/56
It basically reset and run to get only the lastest seen feeds in the db. I use this command regularly without any issue although, there is a little risk that I miss an entry if the feed gets updated between the run and the cleandb commands. A more careful work must be done on this, but I never found the time to get it done.

I report here again as I believe this issue is major in my use case.

Thank you for reading and thank you for keeping this beautiful software alive!

**Comment by Profpatsch** [comment]
How many feeds are you archiving? What is the size of your database?

I’m not very convinced storing the data as json is a good idea in the first place.

**Comment by sciunto** [comment]
About 80 feeds, I cleaned up few days ago, and it's about 500K right now. I can monitor the size over the next weeks.

I also agree with you regarding the choice of json.
