### ISSUE TITLE
timeout: print the name of the feed that times-out

### ISSUE THREAD

**Issue by monperrus** [rss2email/rss2email#51]
In my dozens of feeds, one times-out:

    [ERROR] 60 second timeout exceeded

It would be great to know which one to remove or update the feed URL.

**Comment by monperrus** [comment]
PR in #57

**Comment by xrat** [comment]
Can't we just add the feed's name to `error.py`?

**Comment by monperrus** [comment]
That would be another solution, less straightforward.

**Comment by polm** [comment]
The fix mentioned in the commit here, of using `r2e -V run` to debug feeds, doesn't seem to work for me. Am I doing something wrong or did it stop working at some point?
