### ISSUE TITLE
feature: Pause between requests

### ISSUE THREAD

**Issue by dan-da** [rss2email/rss2email#53]
I have run into an issue where my requests are denied by server apparently due to hitting the server too frequently.   For this setup, I have over 60 feeds configured that all point to the same domain/server.   So when r2e is run, all those fetches occur in a loop as fast as possible.    The server sees this as abuse and rate limits, in this case returning 403 forbidden.

I would suggest a new config option: same-server-fetch-interval

Or if that's too complicated to implement, a simpler thing would be just a pause interval between each feed request, regardless of domain/server.

**Comment by Profpatsch** [comment]
The server should return `429 Too Many Requests` instead.

The actual request is not done by `rss2email`, but by the feedparser library: https://pythonhosted.org/feedparser/introduction.html

**Comment by dan-da** [comment]
> The server should return 429 Too Many Requests instead.

sure it should, but it doesn't have to.  And it is possible that my client is being blocked due to site misconfiguration or whatever.

Regardless, the point here is to be a well behaved client that pauses between requests rather than firing them off as quickly as possible.

From administering servers myself, I know that there are many bad clients/bots/dos that fire requests nonstop and use valuable server resources and bandwidth.   As such, server admins often take measures to automatically block them, and rightly so.    Usually these approaches allow requests at a moderate rate, but block if there are more than X requests in time Y.

> The actual request is not done by rss2email, but by the feedparser library

I already made a little hack to rss2email that just calls sleep for 60 seconds after each feed is processed.   That may not be a perfect solution as feedparser may do retries, redirects or whatever, but it should be effective in most cases to prevent hammering a server.
