### ISSUE TITLE
craigslist rss requests fail with 403 error.

### ISSUE THREAD

**Issue by dan-da** [rss2email/rss2email#54]
I have duplicated this on separate machines in different physical locations.

'r2e run' fails fetching the feed with a 403 error.  However the url loads just fine in wget and in any web browser.  so it is not IP related.   proof (steps to reproduce) below.

Using r2e version 3.9, from ubuntu repo, and also master from github/rss2email.

All craigslist.org feed URLs have been failiing since approx May 9.  I notified Craig (of craigslist) and he replied that he sent it to his eng team.  On May 17, the feeds started working again and I thought the problem resolved, but by May 18 the 403's were back, and continue on.

I also tried modifying the USER_AGENT string in feed.py to eg 'Mozilla/5.0' and also omitting the string (to use feedparser default) but no change.

This seems to be a server-side issue since my installation was working well until May 9, however it is very interesting that wget works when r2e does not, and indicates there must be a client-side way to achieve a correct fetch. 

I had initially thought the problem to likely be related to too many requests in a given time interval, however I tried with a brand new rss2email install on a remote server and it failed on the very first request, as shown below.

Anyway, I hope we can get ti working again.

```
$ r2e add cl1 'https://sfbay.craigslist.org/search/sss?format=rss&query=sw5548&searchNearby=1' <email>

$ r2e run
HTTP status 403 fetching feed cl1 (https://sfbay.craigslist.org/search/sss?format=rss&query=sw5548&searchNearby=1 -> [EMAIL]

$ wget -O feed.xml "https://sfbay.craigslist.org/search/sss?format=rss&query=sw5548&searchNearby=1"
--2019-05-27 07:49:19--  https://sfbay.craigslist.org/search/sss?format=rss&query=sw5548&searchNearby=1
Resolving sfbay.craigslist.org (sfbay.craigslist.org)... 208.82.238.18
Connecting to sfbay.craigslist.org (sfbay.craigslist.org)|208.82.238.18|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/rss+xml]
Saving to: ‘feed.xml’

feed.xml                              [ <=>                                                         ]   1.40K  --.-KB/s    in 0s      

2019-05-27 07:49:20 (55.3 MB/s) - ‘feed.xml’ saved [1433]

$ head -n 6 feed.xml 
<?xml version="1.0" encoding="UTF-8"?>

<rdf:RDF
 xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
 xmlns="http://purl.org/rss/1.0/"
 xmlns:enc="http://purl.oclc.org/net/rss_2.0/enc#"
```

**Comment by Profpatsch** [comment]
rss2email is still not fetching any feeds. It’s all done by the [feedparser](https://pypi.org/project/feedparser/) library, so you should rather open this issue there.

**Comment by Ekleog** [comment]
Upstream issue is closed, and my tl;dr of it is it's due to craigslist banning some combination of ip, ciphers etc. Let's close this too, as there's AFAIU nothing to be done in rss2email :)
