### ISSUE TITLE
Delete stale branches

### ISSUE THREAD

**Issue by Ekleog** [rss2email/rss2email#69]
A few unmerged branches appear to belong to various persons, in this repo:
- `Yannik` by @Yannik 
- `sr` by @sr 
- `AndreyMZ` by @AndreyMZ
- `man-overhaul` by @Profpatsch 

Is it OK for you to delete them / have they correctly been merged upstream in different PRs?

Also, I've already deleted merged branches, but think it'd be best if we could push the PR'd branches to our personal repositories only (and not the `rss2email` one), so as to avoid noise for people who clone the repo.

**Comment by AndreyMZ** [comment]
According to the git log:
- Branches `sr`, `AndreyMZ`, `Yannik` were merged into `master` (indirectly).
- The only commit from branch `man-overhaul` (7d6813051c4647da92d42b4f427549f80b7ca98a "WIP: manpage fixes") was cherry-picked into `master` (bd03505d5e493a306f98ec32d6bafbd3eed59a71 "WIP: manpage fixes").

So, it is OK for me to delete them.

**Comment by kaashif** [comment]
Due to all of the likes and affirmative comments, I deleted the stale branches.
