### ISSUE TITLE
Add HTTPS proxy support

### ISSUE THREAD

**Issue by lhaeffele** [rss2email/rss2email#70]
proxy config does not work for HTTPS feeds.
In order to make it work, I've tried the following : 
Replace
kwargs['handlers'] = [_urllib_request.ProxyHandler({'http':proxy})]
by
kwargs['handlers'] = [_urllib_request.ProxyHandler({'http':proxy, 'https':proxy})]

**Comment by Ekleog** [comment]
@lhaeffele Can you submit a PR, so that authorship information is maintained? :)
