### ISSUE TITLE
Migrate to newer feedparser

### ISSUE THREAD

**Issue by Profpatsch** [rss2email/rss2email#73]
It seems to me like feedparser has the same issue we did: they have over 100 unreleased commits since their last release in 2015 including fixes for breaking issues like this one. Too bad it's considered impolite to harass people into regularly releasing their code.

_Originally posted by @kaashif in https://github.com/rss2email/rss2email/issues/72#issuecomment-528318277_

**Comment by kaashif** [comment]
This is kind of serious since it means `r2e` just crashes sometimes (and it looks like our fault). We could fix the crash in feedparser by wrapping calls in a try-except but the parse would be wrong, that's a hack that doesn't even work properly. Should we vendor feedparser?

**Comment by Ekleog** [comment]
Can we not just depend on a git commit of feedparser?

**Comment by kaashif** [comment]
Maybe we should then make a submodule, import that in the code, and remove the dependency on feedparser in setup.py?

**Comment by Profpatsch** [comment]
I agree with the submodule, but I’d put it in a toplevel `vendor/` directory with a readme that explains why each vendor is needed and when it can be removed again.

**Comment by Astranox** [comment]
there has been an update for feedparser on Oct 2, namely feedparser 6.0.0b1, but it's not on pypi yet.

**Comment by Ekleog** [comment]
Feedparser released 6.0.0 \o/ now it's our turn to upgrade
