### ISSUE TITLE
removal of unescape() broke rss2email

### ISSUE THREAD

**Issue by jahir** [rss2email/rss2email#77]
Hi!

In #63 (commit https://github.com/Alir3z4/html2text/commit/5443b50490cb11f3b964674b80e7f92d38be0d08) unescape() was removed because it was said to be unused. Unfortunately, it is used by rss2email (at least the version that is shipped with Fedora).  I know r2e is somewhat outdated (last release in 2011), but it was working quite fine.
Is there any chance of re-adding this function?

**Comment by jahir** [comment]
sorry, this should have been opend with html2text (see  https://github.com/Alir3z4/html2text/issues/291).
OTOH, if html2text will keep it dropped, we could built our own private version into r2e, it was not that much code...

**Comment by Ekleog** [comment]
@jahir Last release of rss2email (from a few weeks ago) dropped the dependency on html2text for unescape. Does this solve your issue? https://github.com/rss2email/rss2email/pull/64

**Comment by jahir** [comment]
Well, Fedora still brings v2.71 (from http://www.allthingsrss.com/rss2email/), but seems to be in the process of updating. Meanwhile, I'm running a private copy.
