### ISSUE TITLE
[3.10] Support for Python 3.4 and 3.5 is broken

### ISSUE THREAD

**Issue by hartwork** [rss2email/rss2email#80]
Hi!

`setup.py` of 3.10 says that Python 3.4 and 3.5 are supported…
https://github.com/rss2email/rss2email/blob/9c2d4072cb126b9806ec783627f0bd2f68debdf6/setup.py#L52-L56
…but use of f-strings (that [has been reverted](dd67532297daa0b039567913fdfb68d34cb2f9d2) by now) breaks support for Python <3.6. Are there plans for a new release with the fixes?

Best, Sebastian

**Comment by Profpatsch** [comment]
@Ekleog can we do a new patch-release?

**Comment by hartwork** [comment]
My impression is that the release of v3.11 fixed this issue. True?

**Comment by Ekleog** [comment]
It should have at least, thanks!
