### ISSUE TITLE
TLSv1.2 fails SMTP authentication with Office 365

### ISSUE THREAD

**Issue by joeldeteves** [rss2email/rss2email#81]
I am not sure if this is a bug or not, but it seems odd and potentially insecure: Specifying TLSv1.2 in the config fails SMTP authentication with Office 365.

I say it's odd because Microsoft clearly only supports TLSv1.2: 
https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3
https://docs.microsoft.com/en-us/office365/troubleshoot/security/prepare-tls-1.2-in-office-365

Weirdly, it works fine when I change TLS to v1 - that seems insecure, but it also seems like Microsoft would reject the connection if it was not using 1.2?

Seems like something to investigate.

**Steps to reproduce**
1. Add an Office 365 account using SMTP
2. Set smtp-server = smtp.office365.com:587
2. Set smtp-ssl-protocol = TLSv1.2

Thank you,

**Comment by joeldeteves** [comment]
BTW I checked the header on one of the messages and it does appear that Office 365 is in fact using TLSv1.2:

` Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id`

**Comment by Profpatsch** [comment]
Maybe you could open an upstream ticket, it should be in the interest of MS to be compatible with the python TLS libraries.

**Comment by joeldeteves** [comment]
Thanks, I will do that.

**Comment by Ekleog** [comment]
@joeldeteves Any news about this issue?

**Comment by joeldeteves** [comment]
> @joeldeteves Any news about this issue?

Sorry, I haven't heard anything from Microsoft.

Although rss2email continues to work fine with Office 365 when set to TLSv1.

**Comment by Ekleog** [comment]
Hmm… ok, well, I guess we can't do much but close this here as it's AFAIU an upstream issue. Anyway, thank you for having mentioned the issue here, and reported it to Microsoft!
