### ISSUE TITLE
Feature Request: Modify the subject line

### ISSUE THREAD

**Issue by joeldeteves** [rss2email/rss2email#82]
I checked the docs and tried a lot of things but I couldn't seem to figure out a way to do this.

Some email providers, such as Microsoft Office 365 will strip / replace the From name & address with that of the account that's being used to send.

In these cases it would be better to use the subject line to display the feed name, author etc as opposed to trying to modify the From address. In addition, it would be good to be able to add your own subject items so R2E messages can be tagged for setting up mail sorting filters.

If there is a way to do this then I apologize in advance for opening an issue - if that is the case, please inform / update docs on how to do this.

Thank you,

**Comment by finchy** [comment]
I'd like to ++ this.  One of the use cases I have for r2e is to process blogs and send them to Evernote for indexing.  I'd like to assign these incoming blog posts to a certain notebook, which I can do by [appending @notebook_name to the end of the subject line.](https://help.evernote.com/hc/en-us/articles/209005347-How-to-save-email-into-Evernote)

This would be super handy.

**Comment by Ekleog** [comment]
This is probably doable from a post-process hook, but we should probably also consider making it an actual feature (or just a provided post-process hook). Help certainly wanted :)

**Comment by auouymous** [comment]
@joeldeteves You are correct, it does fix this issue. The documentation does kind of show how to use it, but doesn't mention that attributes must be wrapped in curly braces. The default is `subject-format = {feed-title}`, and `subject-format = {feed-name}: {feed-title}` or `subject-format = [{feed-name}] {feed-title}` could be used to prepend the name you gave the feed. I have no idea what `{feed}` would display.

```
        # The format for the Subject line.  Available attributes are
        # 'feed', 'feed-name', 'feed-url', 'feed-title'.
        ('subject-format', '{feed-title}'),
```

Fixed by #198.

**Comment by joeldeteves** [comment]
> @joeldeteves You are correct, it does fix this issue. The documentation does kind of show how to use it, but doesn't mention that attributes must be wrapped in curly braces. The default is `subject-format = {feed-title}`, and `subject-format = {feed-name}: {feed-title}` or `subject-format = [{feed-name}] {feed-title}` could be used to prepend the name you gave the feed. I have no idea what `{feed}` would display.
> 
> ```
>         # The format for the Subject line.  Available attributes are
>         # 'feed', 'feed-name', 'feed-url', 'feed-title'.
>         ('subject-format', '{feed-title}'),
> ```
> 
> Fixed by #198.

Thanks! It looks like this change is also not yet published as of version 3.13.1.

Can we expect a 3.13.2 release soon?

I could pull from `master` but we use r2e in Docker so we like to manage using the tags.

**Comment by auouymous** [comment]
There will probably be a release after #209 is merged.

**Comment by fuzxi** [comment]
> @joeldeteves I have no idea what `{feed}` would display.

`{feed}` displays the output of `r2e list` for the entry in question, i.e. `{feed-name} ({feed-url} -> $(email))`.
