### ISSUE TITLE
Threading.isAlive was removed in Python 3.9 in favour of is_alive

### ISSUE THREAD

**Issue by tirkarthi** [rss2email/rss2email#85]
https://bugzilla.redhat.com/show_bug.cgi?id=1794339

https://github.com/rss2email/rss2email/blob/79e5af41a7f93e965c4b3cef46d8cc1535a88885/rss2email/util.py#L75

I will add a PR for this.

**Comment by Profpatsch** [comment]
when was `is_alive` introduced? We are backwards compatible till 3.5 at the moment.

**Comment by tirkarthi** [comment]
It is present from Python2.7 itself. isAlive was a deprecated alias to is_alive.
