### ISSUE TITLE
Add version-to-version migration support

### ISSUE THREAD

**Issue by jsbackus** [rss2email/rss2email#9]
We should elegantly handle changes to the config file so that users don't get any nasty surprises..

**Comment by Profpatsch** [comment]
What exactly does this encompass? I’d say adding a `version` field to the config (that is the same as the version of `rss2email` that created it) and some migration code that knows how to go from any version to any other version. Depends on https://github.com/rss2email/rss2email/issues/27.

**Comment by jsbackus** [comment]
Agreed. Prefer any version to any version, but at the least 'pre organization' to any version

**Comment by Profpatsch** [comment]
> and some migration code that knows how to go from any version to any other version.

After talking to a friend about it I came to the conclusion that programs should not modify config files (that is not expected on Unixoids). But nonetheless, we can show appropriate warnings on unimportant changes or crash on startup for possible deal-breakers (after a breaking version update the user should check all services, and most probably misses a warning but certainly sees when a service is not running anymore).

**Comment by Ekleog** [comment]
Do we actually have backwards-incompatible changes to the configuration format since 3.9? There's nothing that looks like it to me if I read the changelog, so I think we can postpone that to 3.11 -- changing the milestone for now, feel free to revert if I missed something.

**Comment by Ekleog** [comment]
The idea of having programs not modify their configuration files being what it is, I'll close this for now, and we can re-evaluate later on if there are clear use cases for such a `version` flag. But it'd be unusual, and I don't think rss2email is special enough to warrant a solution that hasn't proven itself with other programs for now.
